### ISSUE TITLE
support different build type

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/poco_vendor#11]
The "fat" binary archive generated for a release is build in release mode. When a user tries to build code on top in debug mode this package doesn't pick the built version of `Poco` but tries to find a debug version of the library on the system which might not be available.

Follow up of ros2/examples#199. @athackst FYI.

**Comment by mikaelarguedas** [comment]
@dirk-thomas can you clarify what is the suggested follow-up here ? To ship both Release and Debug version of the Poco library in the fat binary?

**Comment by dirk-thomas** [comment]
Yes, both versions should be built and packaged.

**Comment by mikaelarguedas** [comment]
Sounds good, is it something we want to target for the upcoming ardent patch? or just for bouncy?
If the latter I'll update the Ament tutorial to use the `Release` build type and not the `Debug` one as the tutorial is still broken for users who don't have the debug version of the lib.

**Comment by dirk-thomas** [comment]
If we get it patched rather soon we could consider it for the Ardent patch release. Otherwise since there is a clear workaround Bouncy would be fine too.

**Comment by sloretz** [comment]
Looks like the same issue still happens on Windows. In the output of [this packaging job](https://ci.ros2.org/view/packaging/job/packaging_windows/985/consoleText) I see 

    -- Installing: C:/J/workspace/packaging_windows/ws/build/poco_vendor/poco_install_Debug/lib/PocoFoundation.lib
    -- Installing: C:/J/workspace/packaging_windows/ws/build/poco_vendor/poco_install_Debug/bin/PocoFoundation.dll

which suggests that `Debug_POSTFIX` is not set on windows. I reproduced the issue on windows using similar steps to ros2/examples#199 and found that `FindPoco.cmake` errored here because it couldn't find the library `PocoFoundationd`

https://github.com/ros2/poco_vendor/blob/db0cd06996ca2e6b904db0604f6246a8ce29b004/cmake/Modules/FindPoco.cmake#L194-L202

I think passing `-DCMAKE_Debug_POSTFIX=d` to `ExternalProject_Add` might force the library to have a `d` suffix on windows.
