### ISSUE TITLE
Missing dependencies in xenial

### ISSUE THREAD

**Issue by paulbovbel** [ros2/poco_vendor#20]
Apologies I'm not aware of the background for this PR (https://github.com/ros2/poco_vendor/pull/18) - on xenial, libpoco-dev does not pull in PCRE or zlib.

As someone who builds ROS2 from source in CI on xenial and bionic, and depends on catkin_pkg/rosdep to resolve dependencies, I wonder: is there any harm in keeping those build_depends in poco_vendor, given that xenial is nominally a supported platform?

**Comment by nuclearsandwich** [comment]
> Apologies I'm not aware of the background for this PR (#18) - on xenial, libpoco-dev does not pull in PCRE or zlib.

No apology needed and thanks for asking for context. #18 was discussed offline today and I forgot to update the PR thread with the key points from that discussion. TWe decided to depend just on libpoco-dev since that's what the binary release on bionic will need and to add the poco build dependencies for Xenial to the [Linux development environment setup guide](https://github.com/ros2/ros2/wiki/Linux-Development-Setup#how-to-setup-the-development-environment).

**Comment by paulbovbel** [comment]
Right, and that's understood. So my question is: is there any harm with leaving the dependencies from #18 in, while xenial _is_ a supported platform?

For reference, my CI flow is essentially this:
```
rosinstall_generator ... # grab a subset of packages from rosdistro
vcs import ...
rosdep install --ignore-src  # install dependencies
colcon ...
```
Now, this works for ROS1 and ROS2, barring the following exceptions:
- a few inconsistencies in libopensplice keys, that I've been meaning to PR
- poco_vendor

I see that the linux dev setup guide has a lot of manual dependency installation going on, but coming from ROS1, I've typically depended on rosdep to pull in dependencies as declared in package.xml. This works particularly well if you're not building _everything_, but a subset of packages in the distro.

Is this unsupported?

**Comment by mikaelarguedas** [comment]
> So my question is: is there any harm with leaving the dependencies from #18 in, while xenial is a supported platform?

I don't think there is any harm as the libraries are pulled in by `libpoco-dev` anyway so it will just pull some additional development files but nothing big. So I think it's fine to add the dependencies back for xenial

> I see that the linux dev setup guide has a lot of manual dependency installation going on, but coming from ROS1, I've typically depended on rosdep to pull in dependencies as declared in package.xml. This works particularly well if you're not building everything, but a subset of packages in the distro.
Is this unsupported?

This is not currently supported as several packages either don't have package.xml (third party dependencies) or use unresolved keys (DDS packages not released upstream).
This could be used for a subset of packages but there will be several cases where it won't work/ be optimal:
- packages not necessary will be installed (e.g. all opencv will be installed when only few packages from it are necessary)
- dependencies needed from pip will still need to be installed manually
- dependencies  for packages that don't have a package.xml (e.g. Fast-RTPS) still need to be installed by hand

**Comment by paulbovbel** [comment]
Understood, thanks for the consideration. Just brainstorming, I understand if getting this workflow working isn't a priority for you folks:

1. For packages that have a package.xml patched in (fastrtps/fastcdr), I've been pulling down the bloomed release branch rather than the upstream source branch.
2. Haven't noticed the issue with opencv, but wouldn't the solution be to reduce the scope of the dependencies declared in the appropriate package.xml's?
3. Pip dependencies - I don't currently run tests on upstream (OSRF) ROS2 packages, so that's why I probably haven't hit this. Certainly just build/package works without them. Would it be possible to package these up as debs on packages.ros2.org? I recall a similar approach being done for certain dependencies in ROS1
4. DDS packages not released upstream - I draw libopensplice67 from packages.ros2.org, although some rosdep-hacking has been necessary due to inconsistent keys (There's a mix of opensplice and libopensplice64 rosdeps in the wild) and connext.

How do you manage dependency installation on the ros2 buildfarm, given these shortcomings? As ros2/rosdistro grows, do you see the `rosdep install` workflow becoming supported/first-class in the future?

**Comment by mikaelarguedas** [comment]
> For packages that have a package.xml patched in (fastrtps/fastcdr), I've been pulling down the bloomed release branch rather than the upstream source branch.

:+1: that's a good workaround

> Haven't noticed the issue with opencv, but wouldn't the solution be to reduce the scope of the dependencies declared in the appropriate package.xml's?

This is actually a common issue in ROS1 as well in both rosdep and package.xml.
- On the rosdep side: now that (since Melodic) we target the upstream version of OpenCV, we should create keys for each opencv package so that people could exec_depend only on the ones needed by the package.
- On the package.xml side, developers tend to use the same keys for build and exec depends. Most packages need the dev version only for building and could use just the libraries (without the dev files) as runtime dependencies. This is something we haven't addressed in ROS2 packages so far as multiple use the same practice.

> Pip dependencies - I don't currently run tests on upstream (OSRF) ROS2 packages, so that's why I probably haven't hit this. Certainly just build/package works without them. Would it be possible to package these up as debs on packages.ros2.org? I recall a similar approach being done for certain dependencies in ROS1

We try to do this in ROS1 only when the package doesnt exist at all upstream and is really needed. For packages where a (n older) version exists upstream, this is discouraged as this will impact the rest of the users system in unexpected ways

> DDS packages not released upstream - I draw libopensplice67 from packages.ros2.org, 

Yes this is currently the only place where these debs are available. This is why we didnt add then to the rosdep database (as they are not available in any upstream repo and not on packages.ros.org). It is unclear to me how / where these keys should live at the moment.

> although some rosdep-hacking has been necessary due to inconsistent keys (There's a mix of opensplice and libopensplice64 rosdeps in the wild) and connext.

Yes this is in progress of being homogenized. We originally didnt have debs for connext so just ignored the keys. Now that we have a deb we'll homogenize the names for the upcoming Bouncy release.
Same thing for opensplice as we now use opensplice 6.7

> How do you manage dependency installation on the ros2 buildfarm, given these shortcomings? As ros2/rosdistro grows, do you see the rosdep install workflow becoming supported/first-class in the future?

We used to ship only Fast-RTPS so these (opensplice / connext) dependencies were not used.
The other ones were fixed using the package.xml injected in the release repos.

> As ros2/rosdistro grows, do you see the rosdep install workflow becoming supported/first-class in the future?

Yes I believe this will become a supported use case in the future (at least for Linux). There are details to figure out before reaching that point:
- How the handling of group dependencies will work in rosdep
- ROS 2 platforms that don't have rosdep installers ATM (e.g. Windows)

**Comment by paulbovbel** [comment]
Thanks for the patch and the super detailed response. Looking forward to Bouncy, and I'll keep following this thread.

**Comment by mikaelarguedas** [comment]
Thanks fr trying it out and giving feedback!

This thread was closed automatically by the PR as the original issue was addressed.

When the topic of using rosdep as supported workflow comes up in another high level issue, we should make sure to link to this.

**Comment by mikaelarguedas** [comment]
@paulbovbel Bouncy [Linux source instructions](https://github.com/ros2/ros2/wiki/Linux-Development-Setup) have been updated to use rosdep: the work for the other wiki pages is ticketed at https://github.com/ros2/ros2/issues/536.
Some of the uncovered cases listed above have not been addressed in rosdep itself but we kept some manual installation steps to make sure they are satisfied.
